package io.veyralang.runtime;

import io.veyralang.ast.Ast;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

public final class Interpreter {
    private final Ast.Function function; private final Map<String,Ast.Function> functions; private final Map<String,Object> env=new HashMap<>();
    private final List<ActionCommand> commands;
    private final ExecutionState state;
    public Interpreter(Ast.Function function){this(function,List.of(function),new ArrayList<>());}
    public Interpreter(Ast.Function function,List<Ast.Function> all){this(function,all,new ArrayList<>());}
    public Interpreter(Ast.Function function,List<Ast.Function> all,List<ActionCommand> commands){this(function,all,commands,new ExecutionState());}
    private Interpreter(Ast.Function function,List<Ast.Function> all,List<ActionCommand> commands,ExecutionState state){this.function=function;this.functions=new HashMap<>();for(Ast.Function f:all)functions.put(f.name(),f);this.commands=commands;this.state=state;}
    public Object call(Object... args){ if(args.length!=function.parameters().size())throw new RuntimeException("参数数量不匹配"); if(++state.depth>64){state.depth--;throw new RuntimeException("脚本递归深度超过 64 层");} for(int i=0;i<args.length;i++)env.put(function.parameters().get(i).name(),args[i]); try{execute(function.body());}catch(ReturnValue r){return r.value;} finally{state.depth--;} return null; }
    public ScriptResult execute(Object... args){Object value=call(args);return new ScriptResult(value,commands);}
    private void execute(List<Ast.Stmt> statements){for(Ast.Stmt s:statements){if(++state.steps>100_000)throw new RuntimeException("脚本执行步数超过 100000");if(s instanceof Ast.Let x)env.put(x.name(),eval(x.value())); else if(s instanceof Ast.Assign x){if(!env.containsKey(x.name()))throw new RuntimeException("未定义变量: "+x.name());env.put(x.name(),eval(x.value()));} else if(s instanceof Ast.Return x)throw new ReturnValue(eval(x.value())); else if(s instanceof Ast.Emit x){if(commands.size()>=1000)throw new RuntimeException("脚本动作数量超过 1000");List<Object> values=x.arguments().stream().map(this::eval).toList();commands.add(new ActionCommand(x.action(),values));} else if(s instanceof Ast.If x){boolean done=false;for(Ast.Branch b:x.branches())if(asBool(eval(b.condition()))){execute(b.body());done=true;break;}if(!done)execute(x.otherwise());}}}
    private Object eval(Ast.Expr e){ if(e instanceof Ast.Literal x)return x.value() instanceof String ? interpolate((String)x.value()) : x.value(); if(e instanceof Ast.Variable x){if(!env.containsKey(x.name()))throw new RuntimeException("未定义变量: "+x.name());return env.get(x.name());} if(e instanceof Ast.ListLiteral x){List<Object> values=new ArrayList<>();for(Ast.Expr item:x.elements())values.add(eval(item));return java.util.Collections.unmodifiableList(values);} if(e instanceof Ast.Index x){Object target=eval(x.target());int index=(int)number(eval(x.index()));if(target instanceof List<?> list){if(index<0||index>=list.size())throw new RuntimeException("列表下标越界: "+index);return list.get(index);}if(target!=null&&target.getClass().isArray()){if(index<0||index>=java.lang.reflect.Array.getLength(target))throw new RuntimeException("数组下标越界: "+index);return java.lang.reflect.Array.get(target,index);}throw new RuntimeException("下标目标不是列表或数组");} if(e instanceof Ast.Property x)return property(eval(x.target()),x.name(),x.safe()); if(e instanceof Ast.Call x){if(x.target() instanceof Ast.Property p && p.name().equals("contains")){Object owner=eval(p.target());if(!(owner instanceof List<?> list))throw new RuntimeException("contains 仅支持列表");return list.contains(eval(x.arguments().get(0)));}if(!(x.target() instanceof Ast.Variable v)||!functions.containsKey(v.name()))throw new RuntimeException("只能调用已定义函数或受控列表操作");Ast.Function f=functions.get(v.name());Object[] args=x.arguments().stream().map(this::eval).toArray();return new Interpreter(f,new java.util.ArrayList<>(functions.values()),commands,state).call(args);} if(e instanceof Ast.Unary x){Object v=eval(x.value());return x.op().equals("!")?!asBool(v):-number(v);} Ast.Binary x=(Ast.Binary)e; Object l=eval(x.left()); if(x.op().equals("&&"))return asBool(l)&&asBool(eval(x.right())); if(x.op().equals("||"))return asBool(l)||asBool(eval(x.right())); if(x.op().equals("??"))return l!=null?l:eval(x.right()); Object r=eval(x.right()); return binary(l,x.op(),r); }
    private Object property(Object target,String name,boolean safe){if(target==null){if(safe)return null;throw new RuntimeException("不能从 null 读取属性 "+name);}if(target instanceof List<?> list&&name.equals("size"))return list.size();if(target.getClass().isArray()&&name.equals("size"))return java.lang.reflect.Array.getLength(target);String cap=Character.toUpperCase(name.charAt(0))+name.substring(1);try{try{Method m=target.getClass().getMethod("get"+cap);m.setAccessible(true);return m.invoke(target);}catch(NoSuchMethodException e){try{Method m=target.getClass().getMethod("is"+cap);m.setAccessible(true);return m.invoke(target);}catch(NoSuchMethodException e2){try{Method m=target.getClass().getMethod(name);m.setAccessible(true);return m.invoke(target);}catch(NoSuchMethodException e3){Field f=target.getClass().getField(name);f.setAccessible(true);return f.get(target);}}}}catch(Exception e){throw new RuntimeException(target.getClass().getSimpleName()+" 没有可访问属性 "+name,e);}}
    private Object interpolate(String text){var matcher=java.util.regex.Pattern.compile("\\$\\{([A-Za-z_$][A-Za-z0-9_$]*(?:\\.[A-Za-z_$][A-Za-z0-9_$]*)*)}").matcher(text);var result=new StringBuffer();while(matcher.find()){String[] parts=matcher.group(1).split("\\.");Object value=env.get(parts[0]);for(int i=1;i<parts.length;i++)value=property(value,parts[i],false);matcher.appendReplacement(result,java.util.regex.Matcher.quoteReplacement(String.valueOf(value)));}matcher.appendTail(result);return result.toString();}
    private Object binary(Object l,String op,Object r){if(op.equals("+"))return (l instanceof String||r instanceof String)?String.valueOf(l)+r:number(l)+number(r);if(op.equals("-"))return number(l)-number(r);if(op.equals("*"))return number(l)*number(r);if(op.equals("/"))return number(l)/number(r);if(op.equals("%"))return number(l)%number(r);if(op.equals("=="))return equalValues(l,r);if(op.equals("!="))return !equalValues(l,r);double a=number(l),b=number(r);return switch(op){case ">"->a>b;case ">="->a>=b;case "<"->a<b;case "<="->a<=b;default->throw new RuntimeException("未知运算符: "+op);};}
    private boolean equalValues(Object left,Object right){if(left instanceof Number a&&right instanceof Number b)return Double.compare(a.doubleValue(),b.doubleValue())==0;return java.util.Objects.equals(left,right);}
    private double number(Object x){if(x instanceof Number n)return n.doubleValue();throw new RuntimeException("需要数字，却得到: "+x);}
    private boolean asBool(Object x){if(x instanceof Boolean b)return b;throw new RuntimeException("条件必须是 bool");}
    private static final class ReturnValue extends java.lang.RuntimeException{final Object value;ReturnValue(Object v){this.value=v;}}
    private static final class ExecutionState { int steps; int depth; }
}
